name = "Vanilla Modpack"
author = "MentoskaPraha"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3bc30a62489869d13b6d2ab4cfeab20742e0589f41637bc0c82835988c61aa26"

[versions]
minecraft = "1.20.1"
quilt = "0.25.0"
