name = "Vanilla Modpack"
author = "MentoskaPraha"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "86e70f62176382dca3f03c7bd6fb97cbb86b1a6fbb14e06500a1d52768350055"

[versions]
minecraft = "1.20.1"
quilt = "0.25.0"
